/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import beans.Autor;
import beans.Livro;
import dao.AutorDAO;
import dao.LivroDAO;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pedro
 */
public class RelatorioLivro extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioLivro
     */
    public RelatorioLivro() {
        initComponents();
        preencheTabela();
        preencherComboAutores();          
    }
    
    
    public void preencherComboAutores(){
        AutorDAO aDAO = new AutorDAO();
        List<Autor> listaA = aDAO.getAutor();
        cmb_autores.addItem("Selecione um autor");
        for(Autor a : listaA){
            cmb_autores.addItem(a);
        }
 
    }    
    
    public void preencheTabela() {
        LivroDAO lDAO = new LivroDAO();
        List<Livro> listaLivros = lDAO.getLivros();
        DefaultTableModel tabelaLivros = (DefaultTableModel) tbl_livros.getModel();
        tabelaLivros.setNumRows(0);

       
        for (Livro l : listaLivros) {
            Object[] obj = new Object[]{
                l.getId(),
                l.getTitulo(),
                l.getGenero(),
                l.getAutorId(),
                l.getAnoPublicacao(),
                l.getNumCopiasDisponiveis()
            };
            tabelaLivros.addRow(obj);
        }
    }

    public void filtrarTabelaPorAutor(Autor autorSelecionado) {
        DefaultTableModel tabelaLivros = (DefaultTableModel) tbl_livros.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tabelaLivros);
        tbl_livros.setRowSorter(sorter);

        RowFilter<DefaultTableModel, Object> filter = RowFilter.regexFilter(String.valueOf(autorSelecionado.getId()), 3); // 3 é a coluna do ID do autor na tabela

        sorter.setRowFilter(filter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_livros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmb_autores = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Genero", "Autor", "Ano de publicacao", "Copias disponiveis"
            }
        ));
        jScrollPane1.setViewportView(tbl_livros);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Relatório de livros");

        cmb_autores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_autoresItemStateChanged(evt);
            }
        });
        cmb_autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_autoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_autores, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_autoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_autoresActionPerformed

    private void cmb_autoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_autoresItemStateChanged
    cmb_autores.addItemListener(new java.awt.event.ItemListener() {
        @Override
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                // Verifique se o item selecionado não é o item de seleção nula
                if (!cmb_autores.getSelectedItem().equals("Selecione um autor")) {
                    Autor autorSelecionado = (Autor) cmb_autores.getSelectedItem();
                    filtrarTabelaPorAutor(autorSelecionado);
                }
            }
        }
    });
           }//GEN-LAST:event_cmb_autoresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_autores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_livros;
    // End of variables declaration//GEN-END:variables
}
